# Generated by Django 5.1.2 on 2024-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_customuser_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
