# Generated by Django 5.1.2 on 2024-11-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_customuser_is_premium_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_subscribed",
        ),
    ]
