# Generated by Django 5.1.2 on 2024-11-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_remove_customuser_is_subscribed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_image",
        ),
    ]
