# Generated by Django 5.1.2 on 2024-11-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_tweet_name_alter_tweet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweet",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweet",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
